%% Structured mesh
mesh = StructuredMesh([51, 1], [51, 1]);
globalCoord = mesh.coordinates;
bottomNodes = find(globalCoord(2, :) == 0);
topNodes = find(globalCoord(2, :) == 1);
topCenterNodes = topNodes(globalCoord(1, topNodes) > 0.49 & globalCoord(1, topNodes) < 0.51);
timeSteps = 1;

k = 1;
cp = 1;
rho = 1;
m = Material(rho, cp, k*eye(3), 5, 0.25);

% Create boundary conditions
fixed = struct(...
    'nodes', bottomNodes, ...
    'type', 'Dirichlet', ...
    'value', 0, ...
    'components', [0, 1], ...
    'timeSteps', 1:timeSteps ...
);

pulled = struct(...
    'nodes', topNodes, ...
    'type', 'Dirichlet', ...
    'value', 0.1, ...
    'components', [0, 1], ...
    'timeSteps', 1:timeSteps ...
);

% Create body conditions
body = struct(...
    'type', 'main', ...
    'physicalName', 'solid' ...
);

bottom = struct(...
    "nodes", bottomNodes, ...
    "type", "dummy", ...
    "name", "bottom", ...
    "value", 1, ...
    "components", [0, 1], ...
    "timeSteps", 1:timeSteps ...
    );

fem = MechFEMStructured(mesh, timeSteps, "plane stress");

fem.addBoundaryCondition(fixed);
fem.addBoundaryCondition(pulled);
fem.addBoundaryCondition(bottom);
fem.addBodyCondition(body);

fem.getDummy("bottom")

fem.setMaterial(m);

fem.assemble()
fem.solve();
%% Start the plotting
% Analytical solution for a semi-infinite body
figure(1)
colorbar
axis equal
ed = fem.getElemDisp(0);
[sfac] = eldisplace2(fem.Ex, fem.Ey, ed, 1);

%% Applied point force
fixed = struct(...
    'nodes', bottomNodes, ...
    'type', 'Dirichlet', ...
    'value', 0, ...
    'components', [1, 1], ...
    'timeSteps', 1:timeSteps ...
);

pointLoad = struct(...
    'nodes', topCenterNodes, ...
    'type', 'Neumann', ...
    'value', -0.1, ...
    'components', [0, 1], ...
    'timeSteps', 1:timeSteps ...
);

% Create body conditions
body = struct(...
    'type', 'main', ...
    'physicalName', 'solid' ...
);

fem = MechFEMStructured(mesh, timeSteps, "plane stress");

fem.addBoundaryCondition(fixed);
fem.addBoundaryCondition(pointLoad);
fem.addBodyCondition(body);

fem.setMaterial(m);

fem.assemble()
fem.solve();
%% Start the plotting
% Analytical solution for a semi-infinite body
figure(2)
colorbar
axis equal
ed = fem.getElemDisp(0);
[sfac] = eldisplace2(fem.Ex, fem.Ey, ed, 1);